window.dataList = [
  { "w": "一", "p": "一天", "s": "一天一个苹果", "wp": "yī", "pp": "yī tiān", "sp": "yī tiān yī gè pín guǒ"},
  { "w": "二", "p": "二月", "s": "二月有春节", "wp": "èr", "pp": "èr yuè", "sp": "èr yuè yǒu chūn jié"},
  { "w": "三", "p": "三个", "s": "我有三个好朋友", "wp": "sān", "pp": "sān gè", "sp": "wǒ yǒu sān gè hǎo péng yǒu"},
  { "w": "四", "p": "四季", "s": "一年有四季", "wp": "sì", "pp": "sì jì", "sp": "yī nián yǒu sì jì"},
  { "w": "五", "p": "五谷", "s": "花园里有五颜六色的花", "wp": "wǔ", "pp": "wǔ gǔ", "sp": "huā yuán lǐ yǒu wǔ yán liù sè de huā"},
  { "w": "六", "p": "六岁", "s": "我今年六岁了", "wp": "liù", "pp": "liù suì", "sp": "wǒ jīn nián liù suì le"},
  { "w": "七", "p": "七彩", "s": "天上有七彩彩虹", "wp": "qī", "pp": "qī cǎi", "sp": "tiān shàng yǒu qī cǎi cǎi hóng"},
  { "w": "八", "p": "八点", "s": "我每天八点上学", "wp": "bā", "pp": "bā diǎn", "sp": "wǒ měi tiān bā diǎn shàng xué"},
  { "w": "九", "p": "九月", "s": "九月开学真开心", "wp": "jiǔ", "pp": "jiǔ yuè", "sp": "jiǔ yuè kāi xué zhēn kāi xīn"},
  { "w": "十", "p": "十分", "s": "我十分喜欢吃水果", "wp": "shí", "pp": "shí fēn", "sp": "wǒ shí fēn xǐ huān chī shuǐ guǒ"},
  { "w": "口", "p": "大口", "s": "小狗大口吃肉", "wp": "kǒu", "pp": "dà kǒu", "sp": "xiǎo gǒu dà kǒu chī ròu"},
  { "w": "日", "p": "日出", "s": "太阳每天都会日出", "wp": "rì", "pp": "rì chū", "sp": "tài yáng měi tiān dōu huì rì chū"},
  { "w": "月", "p": "月亮", "s": "夜空中有一轮月亮", "wp": "yuè", "pp": "yuè liàng", "sp": "yè kōng zhōng yǒu yī lún yuè liàng"},
  { "w": "水", "p": "喝水", "s": "每天要多喝水", "wp": "shuǐ", "pp": "hē shuǐ", "sp": "měi tiān yào duō hē shuǐ"},
  { "w": "火", "p": "火车", "s": "我坐火车去看奶奶", "wp": "huǒ", "pp": "huǒ chē", "sp": "wǒ zuò huǒ chē qù kàn nǎi nǎi"},
  { "w": "木", "p": "树木", "s": "公园里有很多树木", "wp": "mù", "pp": "shù mù", "sp": "gōng yuán lǐ yǒu hěn duō shù mù"},
  { "w": "土", "p": "土地", "s": "农民伯伯种地", "wp": "tǔ", "pp": "tǔ dì", "sp": "nóng mín bó bo zhòng dì"},
  { "w": "大", "p": "大象", "s": "动物园里有大象", "wp": "dà", "pp": "dà xiàng", "sp": "dòng wù yuán lǐ yǒu dà xiàng"},
  { "w": "小", "p": "小猫", "s": "小猫喜欢喝牛奶", "wp": "xiǎo", "pp": "xiǎo māo", "sp": "xiǎo māo xǐ huān hē niú nǎi"},
  { "w": "中", "p": "中国", "s": "我爱中国", "wp": "zhōng", "pp": "zhōng guó", "sp": "wǒ ài zhōng guó"},
  { "w": "人", "p": "好人", "s": "妈妈是个好人", "wp": "rén", "pp": "hǎo rén", "sp": "mā mā shì gè hǎo rén"},
  { "w": "山", "p": "大山", "s": "我家住在大山里", "wp": "shān", "pp": "dà shān", "sp": "wǒ jiā zhù zài dà shān lǐ"},
  { "w": "天", "p": "天空", "s": "天空很蓝很美", "wp": "tiān", "pp": "tiān kōng", "sp": "tiān kōng hěn lán hěn měi"},
  { "w": "上", "p": "上学", "s": "我每天都去上学", "wp": "shàng", "pp": "shàng xué", "sp": "wǒ měi tiān dū qù shàng xué"},
  { "w": "下", "p": "下雨", "s": "下雨天要打伞", "wp": "xià", "pp": "xià yǔ", "sp": "xià yǔ tiān yào dǎ sǎn"},
  { "w": "左", "p": "左手", "s": "左手拿筷子", "wp": "zuǒ", "pp": "zuǒ shǒu", "sp": "zuǒ shǒu ná kuài zǐ"},
  { "w": "右", "p": "右转", "s": "往右转就到了", "wp": "yòu", "pp": "yòu zhuǎn", "sp": "wǎng yòu zhuǎn jiù dào le"},
  { "w": "手", "p": "洗手", "s": "吃饭前要洗手", "wp": "shǒu", "pp": "xǐ shǒu", "sp": "chī fàn qián yào xǐ shǒu"},
  { "w": "足", "p": "足球", "s": "我喜欢踢足球", "wp": "zú", "pp": "zú qiú", "sp": "wǒ xǐ huān tī zú qiú"},
  { "w": "目", "p": "眼目", "s": "要保护好眼睛", "wp": "mù", "pp": "yǎn mù", "sp": "yào bǎo hù hǎo yǎn jīng"},
  { "w": "耳", "p": "耳朵", "s": "兔子有长耳朵", "wp": "ěr", "pp": "ěr duǒ", "sp": "tù zǐ yǒu cháng ěr duǒ"},
  { "w": "口", "p": "开口", "s": "小鸟开口唱歌", "wp": "kǒu", "pp": "kāi kǒu", "sp": "xiǎo niǎo kāi kǒu chàng gē"},
  { "w": "心", "p": "开心", "s": "今天我很开心", "wp": "xīn", "pp": "kāi xīn", "sp": "jīn tiān wǒ hěn kāi xīn"},
  { "w": "白", "p": "白云", "s": "白云像棉花糖", "wp": "bái", "pp": "bái yún", "sp": "bái yún xiàng mián huā táng"},
  { "w": "田", "p": "稻田", "s": "稻田里有青蛙", "wp": "tián", "pp": "dào tián", "sp": "dào tián lǐ yǒu qīng wā"},
  { "w": "石", "p": "石头", "s": "河边有很多石头", "wp": "shí", "pp": "shí tou", "sp": "hé biān yǒu hěn duō shí tou"},
  { "w": "禾", "p": "禾苗", "s": "禾苗长得很好", "wp": "hé", "pp": "hé miáo", "sp": "hé miáo cháng dé hěn hǎo"},
  { "w": "子", "p": "孩子", "s": "我是个好孩子", "wp": "zǐ", "pp": "hái zǐ", "sp": "wǒ shì gè hǎo hái zǐ"},
  { "w": "女", "p": "女孩", "s": "她是个可爱的女孩", "wp": "nǚ", "pp": "nǚ hái", "sp": "tā shì gè kě ài de nǚ hái"},
  { "w": "男", "p": "男生", "s": "他是个聪明的男生", "wp": "nán", "pp": "nán shēng", "sp": "tā shì gè cōng míng de nán shēng"},
  { "w": "马", "p": "骑马", "s": "爸爸带我去骑马", "wp": "mǎ", "pp": "qí mǎ", "sp": "bà bà dài wǒ qù qí mǎ"},
  { "w": "牛", "p": "奶牛", "s": "奶牛产牛奶", "wp": "niú", "pp": "nǎi niú", "sp": "nǎi niú chǎn niú nǎi"},
  { "w": "羊", "p": "绵羊", "s": "绵羊身上有毛", "wp": "yáng", "pp": "mián yáng", "sp": "mián yáng shēn shàng yǒu máo"},
  { "w": "鸟", "p": "小鸟", "s": "小鸟在树上唱歌", "wp": "niǎo", "pp": "xiǎo niǎo", "sp": "xiǎo niǎo zài shù shàng chàng gē"},
  { "w": "虫", "p": "蝴蝶", "s": "蝴蝶是美丽的虫子", "wp": "chóng", "pp": "hú dié", "sp": "hú dié shì měi lì de chóng zǐ"},
  { "w": "鱼", "p": "金鱼", "s": "鱼缸里有金鱼", "wp": "yú", "pp": "jīn yú", "sp": "yú gāng lǐ yǒu jīn yú"},
  { "w": "草", "p": "小草", "s": "春天小草变绿了", "wp": "cǎo", "pp": "xiǎo cǎo", "sp": "chūn tiān xiǎo cǎo biàn lǜ le"},
  { "w": "花", "p": "红花", "s": "花园里开了红花", "wp": "huā", "pp": "hóng huā", "sp": "huā yuán lǐ kāi le hóng huā"},
  { "w": "树", "p": "大树", "s": "大树下很凉快", "wp": "shù", "pp": "dà shù", "sp": "dà shù xià hěn liáng kuài"},
  { "w": "米", "p": "米饭", "s": "我爱吃米饭", "wp": "mǐ", "pp": "mǐ fàn", "sp": "wǒ ài chī mǐ fàn"},
  { "w": "果", "p": "水果", "s": "水果对身体好", "wp": "guǒ", "pp": "shuǐ guǒ", "sp": "shuǐ guǒ duì shēn tǐ hǎo"},
  { "w": "菜", "p": "蔬菜", "s": "多吃蔬菜身体好", "wp": "cài", "pp": "shū cài", "sp": "duō chī shū cài shēn tǐ hǎo"},
  { "w": "学", "p": "学习", "s": "我喜欢学习", "wp": "xué", "pp": "xué xí", "sp": "wǒ xǐ huān xué xí"},
  { "w": "文", "p": "文字", "s": "我会写很多文字", "wp": "wén", "pp": "wén zì", "sp": "wǒ huì xiě hěn duō wén zì"},
  { "w": "字", "p": "汉字", "s": "汉字很有意思", "wp": "zì", "pp": "hàn zì", "sp": "hàn zì hěn yǒu yì sī"},
  { "w": "国", "p": "中国", "s": "我的国家是中国", "wp": "guó", "pp": "zhōng guó", "sp": "wǒ de guó jiā shì zhōng guó"},
  { "w": "家", "p": "回家", "s": "放学后我要回家", "wp": "jiā", "pp": "huí jiā", "sp": "fàng xué hòu wǒ yào huí jiā"},
  { "w": "工", "p": "工人", "s": "爸爸是工人", "wp": "gōng", "pp": "gōng rén", "sp": "bà bà shì gōng rén"},
  { "w": "生", "p": "生日", "s": "今天是我的生日", "wp": "shēng", "pp": "shēng rì", "sp": "jīn tiān shì wǒ de shēng rì"},
  { "w": "爱", "p": "爱心", "s": "妈妈给了我很多爱心。", "wp": "ài", "pp": "ài xīn", "sp": "mā mā gěi le wǒ hěn duō ài xīn 。"},
  { "w": "北", "p": "北方", "s": "北方的冬天很冷。", "wp": "běi", "pp": "běi fāng", "sp": "běi fāng de dōng tiān hěn lěng 。"},
  { "w": "长", "p": "长大", "s": "我希望快快长大。", "wp": "cháng", "pp": "zhǎng dà", "sp": "wǒ xī wàng kuài kuài zhǎng dà 。"},
  { "w": "出", "p": "出门", "s": "小朋友跟着妈妈一起出门了。", "wp": "chū", "pp": "chū mén", "sp": "xiǎo péng yǒu gēn zhe mā mā yī qǐ chū mén le 。"},
  { "w": "春", "p": "春天", "s": "春天来了，花儿开了。", "wp": "chūn", "pp": "chūn tiān", "sp": "chūn tiān lái le ， huā ér kāi le 。"},
  { "w": "东", "p": "东方", "s": "太阳从东方升起。", "wp": "dōng", "pp": "dōng fāng", "sp": "tài yáng cóng dōng fāng shēng qǐ 。"},
  { "w": "飞", "p": "飞机", "s": "天空中有一架飞机飞过。", "wp": "fēi", "pp": "fēi jī", "sp": "tiān kōng zhōng yǒu yī jià fēi jī fēi guò 。"},
  { "w": "高", "p": "高山", "s": "我们爬上了高山，看到了美丽的风景。", "wp": "gāo", "pp": "gāo shān", "sp": "wǒ men pá shàng le gāo shān ， kàn dào le měi lì de fēng jǐng 。"},
  { "w": "狗", "p": "小狗", "s": "小狗在院子里跑来跑去。", "wp": "gǒu", "pp": "xiǎo gǒu", "sp": "xiǎo gǒu zài yuàn zǐ lǐ pǎo lái pǎo qù 。"},
  { "w": "黄", "p": "黄河", "s": "黄河是中国的母亲河。", "wp": "huáng", "pp": "huáng hé", "sp": "huáng hé shì zhōng guó de mǔ qīn hé 。"},
  { "w": "江", "p": "江水", "s": "江水静静地流淌着。", "wp": "jiāng", "pp": "jiāng shuǐ", "sp": "jiāng shuǐ jìng jìng dì liú tǎng zhuó 。"},
  { "w": "金", "p": "金鱼", "s": "鱼缸里有一条金鱼游来游去。", "wp": "jīn", "pp": "jīn yú", "sp": "yú gāng lǐ yǒu yī tiáo jīn yú yóu lái yóu qù 。"},
  { "w": "开", "p": "开门", "s": "爸爸帮我开门进屋。", "wp": "kāi", "pp": "kāi mén", "sp": "bà bà bāng wǒ kāi mén jìn wū 。"},
  { "w": "蓝", "p": "蓝天", "s": "蓝天上飘着几朵白云。", "wp": "lán", "pp": "lán tiān", "sp": "lán tiān shàng piāo zhuó jī duǒ bái yún 。"},
  { "w": "乐", "p": "快乐", "s": "今天是我的生日，我很快乐！", "wp": "lè", "pp": "kuài lè", "sp": "jīn tiān shì wǒ de shēng rì ， wǒ hěn kuài lè ！"},
  { "w": "离", "p": "离开", "s": "小鸟飞离了树枝。", "wp": "lí", "pp": "lí kāi", "sp": "xiǎo niǎo fēi lí le shù zhī 。"},
  { "w": "明", "p": "明亮", "s": "房间里灯光很明亮。", "wp": "míng", "pp": "míng liàng", "sp": "fáng jiān lǐ dēng guāng hěn míng liàng 。"},
  { "w": "南", "p": "南方", "s": "南方的天气很温暖。", "wp": "nán", "pp": "nán fāng", "sp": "nán fāng de tiān qì hěn wēn nuǎn 。"},
  { "w": "朋", "p": "朋友", "s": "我和朋友一起去公园玩耍。", "wp": "péng", "pp": "péng yǒu", "sp": "wǒ hé péng yǒu yī qǐ qù gōng yuán wán shuǎ 。"},
  { "w": "平", "p": "平安", "s": "祝你一路平安！", "wp": "píng", "pp": "píng ān", "sp": "zhù nǐ yī lù píng ān ！"},
  { "w": "秋", "p": "秋天", "s": "秋天的树叶变黄了。", "wp": "qiū", "pp": "qiū tiān", "sp": "qiū tiān de shù yè biàn huáng le 。"},
  { "w": "少", "p": "少年", "s": "少年们在操场上踢足球。", "wp": "shǎo", "pp": "shào nián", "sp": "shào nián mén zài cāo chǎng shàng tī zú qiú 。"},
  { "w": "时", "p": "时间", "s": "时间过得真快，一眨眼就到放学了。", "wp": "shí", "pp": "shí jiān", "sp": "shí jiān guò dé zhēn kuài ， yī zhǎ yǎn jiù dào fàng xué le 。"},
  { "w": "书", "p": "书包", "s": "我的书包里装满了书本。", "wp": "shū", "pp": "shū bāo", "sp": "wǒ de shū bāo lǐ zhuāng mǎn le shū běn 。"},
  { "w": "同", "p": "同学", "s": "我和同学们一起做游戏。", "wp": "tóng", "pp": "tóng xué", "sp": "wǒ hé tóng xué mén yī qǐ zuò yóu xì 。"},
  { "w": "外", "p": "外面", "s": "外面下雨了，我们在屋里玩。", "wp": "wài", "pp": "wài miàn", "sp": "wài miàn xià yǔ le ， wǒ men zài wū lǐ wán 。"},
  { "w": "西", "p": "西边", "s": "太阳从西边落下去了。", "wp": "xī", "pp": "xī biān", "sp": "tài yáng cóng xī biān là xià qù le 。"},
  { "w": "夏", "p": "夏天", "s": "夏天到了，我们去游泳。", "wp": "xià", "pp": "xià tiān", "sp": "xià tiān dào le ， wǒ men qù yóu yǒng 。"},
  { "w": "星", "p": "星星", "s": "夜空中闪烁着许多星星。", "wp": "xīng", "pp": "xīng xīng", "sp": "yè kōng zhōng shǎn shuò zhuó xǔ duō xīng xīng 。"},
  { "w": "冬", "p": "冬天", "s": "冬天来了，我们要穿暖和的衣服。", "wp": "dōng", "pp": "dōng tiān", "sp": "dōng tiān lái le ， wǒ men yào chuān nuǎn huo de yī fú 。"},
  { "w": "动", "p": "运动", "s": "每天运动身体好。", "wp": "dòng", "pp": "yùn dòng", "sp": "měi tiān yùn dòng shēn tǐ hǎo 。"},
  { "w": "多", "p": "很多", "s": "我认识很多汉字了。", "wp": "duō", "pp": "hěn duō", "sp": "wǒ rèn shi hěn duō hàn zì le 。"},
  { "w": "儿", "p": "儿童", "s": "六一儿童节我们去游乐园玩。", "wp": "ér", "pp": "ér tóng", "sp": "liù yī ér tóng jié wǒ men qù yóu lè yuán wán 。"},
  { "w": "父", "p": "父亲", "s": "父亲节我要送爸爸一份礼物。", "wp": "fù", "pp": "fù qīn", "sp": "fù qīn jié wǒ yào sòng bà bà yī fèn lǐ wù 。"},
  { "w": "好", "p": "好吃", "s": "奶奶做的饭菜很好吃。", "wp": "hǎo", "pp": "hǎo chī", "sp": "nǎi nǎi zuò de fàn cài hěn hǎo chī 。"},
  { "w": "红", "p": "红色", "s": "红色的气球飞上了天。", "wp": "hóng", "pp": "hóng sè", "sp": "hóng sè de qì qiú fēi shàng le tiān 。"},
  { "w": "几", "p": "几个", "s": "你有几个玩具？", "wp": "jī", "pp": "jǐ gè", "sp": "nǐ yǒu jǐ gè wán jù ？"},
  { "w": "见", "p": "见面", "s": "我们明天见面吧！", "wp": "jiàn", "pp": "jiàn miàn", "sp": "wǒ men míng tiān jiàn miàn bā ！"},
  { "w": "姐", "p": "姐姐", "s": "姐姐教我写作业。", "wp": "jiě", "pp": "jiě jiě", "sp": "jiě jiě jiào wǒ xiě zuò yè 。"},
  { "w": "来", "p": "来了", "s": "春天来了，小草长出来了。", "wp": "lái", "pp": "lái le", "sp": "chūn tiān lái le ， xiǎo cǎo cháng chū lái le 。"},
  { "w": "老", "p": "老师", "s": "老师教我们唱歌。", "wp": "lǎo", "pp": "lǎo shī", "sp": "lǎo shī jiào wǒ men chàng gē 。"},
  { "w": "里", "p": "里面", "s": "书包里面有很多书。", "wp": "lǐ", "pp": "lǐ miàn", "sp": "shū bāo lǐ miàn yǒu hěn duō shū 。"},
  { "w": "妈", "p": "妈妈", "s": "妈妈的怀抱最温暖。", "wp": "mā", "pp": "mā mā", "sp": "mā mā de huái bào zuì wēn nuǎn 。"},
  { "w": "么", "p": "什么", "s": "你最喜欢吃什么水果？", "wp": "me", "pp": "shén me", "sp": "nǐ zuì xǐ huān chī shén me shuǐ guǒ ？"},
  { "w": "没", "p": "没有", "s": "我没有看过大象。", "wp": "méi", "pp": "méi yǒu", "sp": "wǒ méi yǒu kàn guò dà xiàng 。"},
  { "w": "年", "p": "新年", "s": "新年到了，我们一起贴春联。", "wp": "nián", "pp": "xīn nián", "sp": "xīn nián dào le ， wǒ men yī qǐ tiē chūn lián 。"},
  { "w": "您", "p": "您好", "s": "遇到长辈要说“您好”。", "wp": "nín", "pp": "nín hǎo", "sp": "yù dào zhǎng bèi yào shuō “nín hǎo”。"},
  { "w": "起", "p": "起床", "s": "早上七点我就起床了。", "wp": "qǐ", "pp": "qǐ chuáng", "sp": "zǎo shàng qī diǎn wǒ jiù qǐ chuáng le 。"},
  { "w": "前", "p": "前面", "s": "前面的路很宽。", "wp": "qián", "pp": "qián miàn", "sp": "qián miàn de lù hěn kuān 。"},
  { "w": "去", "p": "去玩", "s": "周末我们去公园玩。", "wp": "qù", "pp": "qù wán", "sp": "zhōu mò wǒ men qù gōng yuán wán 。"},
  { "w": "认", "p": "认识", "s": "我认识很多小朋友。", "wp": "rèn", "pp": "rèn shi", "sp": "wǒ rèn shi hěn duō xiǎo péng yǒu 。"},
  { "w": "谁", "p": "谁的", "s": "这是谁的书包？", "wp": "shuí", "pp": "shuí de", "sp": "zhè shì shuí de shū bāo ？"},
  { "w": "他", "p": "他们", "s": "他们在操场上玩耍。", "wp": "tā", "pp": "tā mén", "sp": "tā mén zài cāo chǎng shàng wán shuǎ 。"},
  { "w": "她", "p": "她的", "s": "她的画画得真好。", "wp": "tā", "pp": "tā de", "sp": "tā de huà huà dé zhēn hǎo 。"},
  { "w": "听", "p": "听话", "s": "小朋友要听爸爸妈妈的话。", "wp": "tīng", "pp": "tīng huà", "sp": "xiǎo péng yǒu yào tīng bà bà mā mā de huà 。"},
  { "w": "玩", "p": "玩具", "s": "我有很多好玩的玩具。", "wp": "wán", "pp": "wán jù", "sp": "wǒ yǒu hěn duō hǎo wán de wán jù 。"},
  { "w": "晚", "p": "晚上", "s": "晚上我们全家一起看电视。", "wp": "wǎn", "pp": "wǎn shàng", "sp": "wǎn shàng wǒ men quán jiā yī qǐ kàn diàn shì 。"},
  { "w": "问", "p": "问题", "s": "有问题要问老师。", "wp": "wèn", "pp": "wèn tí", "sp": "yǒu wèn tí yào wèn lǎo shī 。"},
  { "w": "先", "p": "先生", "s": "王先生是我们的邻居。", "wp": "xiān", "pp": "xiān shēng", "sp": "wáng xiān shēng shì wǒ men de lín jū 。"},
  { "w": "笑", "p": "笑脸", "s": "妈妈的笑脸真美。", "wp": "xiào", "pp": "xiào liǎn", "sp": "mā mā de xiào liǎn zhēn měi 。"},
  { "w": "些", "p": "一些", "s": "我认识一些动物。", "wp": "xiē", "pp": "yī xiē", "sp": "wǒ rèn shi yī xiē dòng wù 。"},
  { "w": "写", "p": "写字", "s": "我正在学习写字。", "wp": "xiě", "pp": "xiě zì", "sp": "wǒ zhèng zài xué xí xiě zì 。"},
  { "w": "样", "p": "样子", "s": "小猫的样子真可爱。", "wp": "yàng", "pp": "yàng zǐ", "sp": "xiǎo māo de yàng zǐ zhēn kě ài 。"},
  { "w": "也", "p": "也是", "s": "我也是学生。", "wp": "yě", "pp": "yě shì", "sp": "wǒ yě shì xué shēng 。"},
  { "w": "以", "p": "可以", "s": "我可以自己穿衣服了。", "wp": "yǐ", "pp": "kě yǐ", "sp": "wǒ kě yǐ zì jǐ chuān yī fú le 。"},
  { "w": "因", "p": "因为", "s": "因为下雨，我们在家里玩。", "wp": "yīn", "pp": "yīn wèi", "sp": "yīn wèi xià yǔ ， wǒ men zài jiā lǐ wán 。"},
  { "w": "有", "p": "拥有", "s": "我拥有一个幸福的家。", "wp": "yǒu", "pp": "yōng yǒu", "sp": "wǒ yōng yǒu yī gè xìng fú de jiā 。"},
  { "w": "又", "p": "又大", "s": "月亮又大又圆。", "wp": "yòu", "pp": "yòu dà", "sp": "yuè liàng yòu dà yòu yuán 。"},
  { "w": "元", "p": "元旦", "s": "元旦节我们去看烟花。", "wp": "yuán", "pp": "yuán dàn", "sp": "yuán dàn jié wǒ men qù kàn yān huā 。"},
  { "w": "在", "p": "在家", "s": "周末我在家看书。", "wp": "zài", "pp": "zài jiā", "sp": "zhōu mò wǒ zài jiā kàn shū 。"},
  { "w": "早", "p": "早上", "s": "早上我们去公园锻炼。", "wp": "zǎo", "pp": "zǎo shàng", "sp": "zǎo shàng wǒ men qù gōng yuán duàn liàn 。"},
  { "w": "怎", "p": "怎么", "s": "你怎么不开心啊？", "wp": "zěn", "pp": "zěn me", "sp": "nǐ zěn me bù kāi xīn a ？"},
  { "w": "这", "p": "这个", "s": "这个故事很有趣。", "wp": "zhè", "pp": "zhè gè", "sp": "zhè gè gù shì hěn yǒu qù 。"},
  { "w": "主", "p": "主人", "s": "小狗很听主人的话。", "wp": "zhǔ", "pp": "zhǔ rén", "sp": "xiǎo gǒu hěn tīng zhǔ rén de huà 。"},
  { "w": "自", "p": "自己", "s": "我会自己系鞋带了。", "wp": "zì", "pp": "zì jǐ", "sp": "wǒ huì zì jǐ xì xié dài le 。"},
  { "w": "走", "p": "走路", "s": "我们手拉手走路去学校。", "wp": "zǒu", "pp": "zǒu lù", "sp": "wǒ men shǒu lā shǒu zǒu lù qù xué xiào 。"},
  { "w": "最", "p": "最好", "s": "妈妈做的饭菜最好吃。", "wp": "zuì", "pp": "zuì hǎo", "sp": "mā mā zuò de fàn cài zuì hǎo chī 。"},
  { "w": "昨", "p": "昨天", "s": "昨天我去动物园了。", "wp": "zuó", "pp": "zuó tiān", "sp": "zuó tiān wǒ qù dòng wù yuán le 。"},
  { "w": "坐", "p": "坐下", "s": "上课时要安静坐下。", "wp": "zuò", "pp": "zuò xià", "sp": "shàng kè shí yào ān jìng zuò xià 。"},
  { "w": "做", "p": "做饭", "s": "妈妈在厨房做饭。", "wp": "zuò", "pp": "zuò fàn", "sp": "mā mā zài chú fáng zuò fàn 。"},
  { "w": "爸", "p": "爸爸", "s": "爸爸带我去公园玩。", "wp": "bà", "pp": "bà bà", "sp": "bà bà dài wǒ qù gōng yuán wán 。"},
  { "w": "百", "p": "百花", "s": "春天百花齐放。", "wp": "bǎi", "pp": "bǎi huā", "sp": "chūn tiān bǎi huā qí fàng 。"},
  { "w": "班", "p": "班级", "s": "我们班级很团结。", "wp": "bān", "pp": "bān jí", "sp": "wǒ men bān jí hěn tuán jié 。"},
  { "w": "半", "p": "一半", "s": "我吃了一半的苹果。", "wp": "bàn", "pp": "yī bàn", "sp": "wǒ chī le yī bàn de pín guǒ 。"},
  { "w": "帮", "p": "帮忙", "s": "我喜欢帮妈妈做家务。", "wp": "bāng", "pp": "bāng máng", "sp": "wǒ xǐ huān bāng mā mā zuò jiā wù 。"},
  { "w": "包", "p": "书包", "s": "我的书包里有很多书。", "wp": "bāo", "pp": "shū bāo", "sp": "wǒ de shū bāo lǐ yǒu hěn duō shū 。"},
  { "w": "饱", "p": "吃饱", "s": "我吃饱了，谢谢妈妈。", "wp": "bǎo", "pp": "chī bǎo", "sp": "wǒ chī bǎo le ， xiè xiè mā mā 。"},
  { "w": "别", "p": "再见", "s": "放学时我们说“再见”。", "wp": "bié", "pp": "zài jiàn", "sp": "fàng xué shí wǒ men shuō “zài jiàn”。"},
  { "w": "不", "p": "不要", "s": "不要浪费粮食哦。", "wp": "bù", "pp": "bú yào", "sp": "bú yào làng fèi liáng shí ó 。"},
  { "w": "才", "p": "刚才", "s": "刚才我在看书。", "wp": "cái", "pp": "gāng cái", "sp": "gāng cái wǒ zài kàn shū 。"},
  { "w": "层", "p": "楼层", "s": "我家住在三层。", "wp": "céng", "pp": "lóu céng", "sp": "wǒ jiā zhù zài sān céng 。"},
  { "w": "吃", "p": "吃饭", "s": "吃饭前要洗手。", "wp": "chī", "pp": "chī fàn", "sp": "chī fàn qián yào xǐ shǒu 。"},
  { "w": "穿", "p": "穿衣", "s": "冬天要穿暖和的衣服。", "wp": "chuān", "pp": "chuān yī", "sp": "dōng tiān yào chuān nuǎn huo de yī fú 。"},
  { "w": "床", "p": "起床", "s": "早上七点我就起床了。", "wp": "chuáng", "pp": "qǐ chuáng", "sp": "zǎo shàng qī diǎn wǒ jiù qǐ chuáng le 。"},
  { "w": "从", "p": "从前", "s": "从前有座山，山上有座庙。", "wp": "cóng", "pp": "cóng qián", "sp": "cóng qián yǒu zuò shān ， shān shàng yǒu zuò miào 。"},
  { "w": "错", "p": "改错", "s": "做错题要改正。", "wp": "cuò", "pp": "gǎi cuò", "sp": "zuò cuò tí yào gǎi zhèng 。"},
  { "w": "打", "p": "打球", "s": "我喜欢和朋友一起打球。", "wp": "dǎ", "pp": "dǎ qiú", "sp": "wǒ xǐ huān hé péng yǒu yī qǐ dǎ qiú 。"},
  { "w": "到", "p": "到了", "s": "我们到学校了。", "wp": "dào", "pp": "dào le", "sp": "wǒ men dào xué xiào le 。"},
  { "w": "道", "p": "知道", "s": "我知道这个字怎么读。", "wp": "dào", "pp": "zhī dào", "sp": "wǒ zhī dào zhè gè zì zěn me dú 。"},
  { "w": "得", "p": "得到", "s": "我得到了一个奖状。", "wp": "dé", "pp": "dé dào", "sp": "wǒ dé dào le yī gè jiǎng zhuàng 。"},
  { "w": "地", "p": "地方", "s": "这个地方很漂亮。", "wp": "dì", "pp": "dì fāng", "sp": "zhè gè dì fāng hěn piào liàng 。"},
  { "w": "弟", "p": "弟弟", "s": "我有一个可爱的弟弟。", "wp": "dì", "pp": "dì di", "sp": "wǒ yǒu yī gè kě ài de dì di 。"},
  { "w": "第", "p": "第一", "s": "我是班上第一个到教室的。", "wp": "dì", "pp": "dì yī", "sp": "wǒ shì bān shàng dì yī gè dào jiào shì de 。"},
  { "w": "懂", "p": "懂事", "s": "你真是个懂事的好孩子。", "wp": "dǒng", "pp": "dǒng shì", "sp": "nǐ zhēn shì gè dǒng shì de hǎo hái zǐ 。"},
  { "w": "对", "p": "对比", "s": "不小心碰到你，对不起。", "wp": "duì", "pp": "duì bǐ", "sp": "bù xiǎo xīn pèng dào nǐ ， duì bù qǐ 。"},
  { "w": "多", "p": "多少", "s": "你知道多少个汉字？", "wp": "duō", "pp": "duō shǎo", "sp": "nǐ zhī dào duō shǎo gè hàn zì ？"},
  { "w": "饿", "p": "饥饿", "s": "我们要帮助饥饿的人。", "wp": "è", "pp": "jī è", "sp": "wǒ men yào bāng zhù jī è de rén 。"},
  { "w": "房", "p": "房子", "s": "我们住在一个漂亮的房子里。", "wp": "fáng", "pp": "fáng zǐ", "sp": "wǒ men zhù zài yī gè piào liàng de fáng zǐ lǐ 。"},
  { "w": "放", "p": "放学", "s": "放学后我们一起玩。", "wp": "fàng", "pp": "fàng xué", "sp": "fàng xué hòu wǒ men yī qǐ wán 。"},
  { "w": "非", "p": "非常", "s": "我非常喜欢画画。", "wp": "fēi", "pp": "fēi cháng", "sp": "wǒ fēi cháng xǐ huān huà huà 。"},
  { "w": "分", "p": "分享", "s": "我们要学会分享。", "wp": "fēn", "pp": "fēn xiǎng", "sp": "wǒ men yào xué huì fēn xiǎng 。"},
  { "w": "服", "p": "衣服", "s": "我最喜欢这件衣服。", "wp": "fú", "pp": "yī fú", "sp": "wǒ zuì xǐ huān zhè jiàn yī fú 。"},
  { "w": "告", "p": "告诉", "s": "妈妈告诉我要诚实。", "wp": "gào", "pp": "gào sù", "sp": "mā mā gào sù wǒ yào chéng shí 。"},
  { "w": "哥", "p": "哥哥", "s": "哥哥教我踢足球。", "wp": "gē", "pp": "gē gē", "sp": "gē gē jiào wǒ tī zú qiú 。"},
  { "w": "给", "p": "给予", "s": "给予他人帮助很快乐。", "wp": "gěi", "pp": "jǐ yǔ", "sp": "jǐ yǔ tā rén bāng zhù hěn kuài lè 。"},
  { "w": "跟", "p": "跟随", "s": "小鸭子跟随妈妈游泳。", "wp": "gēn", "pp": "gēn suí", "sp": "xiǎo yā zǐ gēn suí mā mā yóu yǒng 。"},
  { "w": "够", "p": "足够", "s": "这些食物足够我们吃了。", "wp": "gòu", "pp": "zú gòu", "sp": "zhèi xiē shí wù zú gòu wǒ men chī le 。"},
  { "w": "贵", "p": "珍贵", "s": "健康是最珍贵的。", "wp": "guì", "pp": "zhēn guì", "sp": "jiàn kāng shì zuì zhēn guì de 。"},
  { "w": "过", "p": "经过", "s": "我们经过一座大桥。", "wp": "guò", "pp": "jīng guò", "sp": "wǒ men jīng guò yī zuò dà qiáo 。"},
  { "w": "还", "p": "还有", "s": "盘子里还有一个苹果。", "wp": "huán", "pp": "huán yǒu", "sp": "pán zǐ lǐ huán yǒu yī gè pín guǒ 。"},
  { "w": "孩", "p": "孩子", "s": "孩子们在操场上玩耍。", "wp": "hái", "pp": "hái zǐ", "sp": "hái zǐ mén zài cāo chǎng shàng wán shuǎ 。"},
  { "w": "很", "p": "很好", "s": "今天的天气很好。", "wp": "hěn", "pp": "hěn hǎo", "sp": "jīn tiān de tiān qì hěn hǎo 。"},
  { "w": "后", "p": "后面", "s": "小狗在我后面跟着。", "wp": "hòu", "pp": "hòu miàn", "sp": "xiǎo gǒu zài wǒ hòu miàn gēn zhe 。"},
  { "w": "欢", "p": "欢迎", "s": "欢迎你来我家玩。", "wp": "huān", "pp": "huān yíng", "sp": "huān yíng nǐ lái wǒ jiā wán 。"},
  { "w": "回", "p": "回家", "s": "我们一起回家吧。", "wp": "huí", "pp": "huí jiā", "sp": "wǒ men yī qǐ huí jiā bā 。"},
  { "w": "会", "p": "会议", "s": "爸爸参加了一个重要会议。", "wp": "huì", "pp": "huì yì", "sp": "bà bà cān jiā le yī gè zhòng yào huì yì 。"},
  { "w": "或", "p": "或者", "s": "你想吃苹果或者香蕉？", "wp": "huò", "pp": "huò zhě", "sp": "nǐ xiǎng chī pín guǒ huò zhě xiāng jiāo ？"},
  { "w": "几", "p": "几乎", "s": "我几乎背出了整首诗。", "wp": "jī", "pp": "jī hū", "sp": "wǒ jī hū bèi chū le zhěng shǒu shī 。"},
  { "w": "加", "p": "加法", "s": "我们今天学习加法。", "wp": "jiā", "pp": "jiā fǎ", "sp": "wǒ men jīn tiān xué xí jiā fǎ 。"},
  { "w": "间", "p": "时间", "s": "我们要珍惜时间。", "wp": "jiān", "pp": "shí jiān", "sp": "wǒ men yào zhēn xī shí jiān 。"},
  { "w": "教", "p": "教室", "s": "我们的教室很明亮。", "wp": "jiào", "pp": "jiào shì", "sp": "wǒ men de jiào shì hěn míng liàng 。"},
  { "w": "接", "p": "接受", "s": "我们要学会接受不同意见。", "wp": "jiē", "pp": "jiē shòu", "sp": "wǒ men yào xué huì jiē shòu bù tóng yì jiàn 。"},
  { "w": "姐", "p": "姐妹", "s": "我和姐姐是一对好姐妹。", "wp": "jiě", "pp": "jiě mèi", "sp": "wǒ hé jiě jiě shì yī duì hǎo jiě mèi 。"},
  { "w": "解", "p": "了解", "s": "我想更多地了解这个世界。", "wp": "jiě", "pp": "liǎo jiě", "sp": "wǒ xiǎng gēng duō dì liǎo jiě zhè gè shì jiè 。"},
  { "w": "届", "p": "年届", "s": "爷爷年届古稀，仍然很健康。", "wp": "jiè", "pp": "nián jiè", "sp": "yé yé nián jiè gǔ xī ， réng rán hěn jiàn kāng 。"},
  { "w": "到", "p": "到了", "s": "我们到学校了。", "wp": "dào", "pp": "dào le", "sp": "wǒ men dào xué xiào le 。"},
  { "w": "说", "p": "说话", "s": "妈妈对我说：“今天你要去上学。”", "wp": "shuō", "pp": "shuō huà", "sp": "mā mā duì wǒ shuō ：“ jīn tiān nǐ yào qù shàng shàng 。”"},
  { "w": "要", "p": "重要", "s": "学习对我们很重要。", "wp": "yào", "pp": "zhòng yào", "sp": "xué xí duì wǒ men hěn zhòng yào 。"},
  { "w": "就", "p": "就是", "s": "他就是一个好学生。", "wp": "jiù", "pp": "jiù shì", "sp": "tā jiù shì yī gè hào xué shēng 。"},
  { "w": "可", "p": "可以", "s": "你可以玩一会儿。", "wp": "kě", "pp": "kě yǐ", "sp": "nǐ kě yǐ wán yī huì ér 。"},
  { "w": "能", "p": "能力", "s": "他能写很多字。", "wp": "néng", "pp": "néng lì", "sp": "tā néng xiě hěn duō zì 。"},
  { "w": "而", "p": "而且", "s": "他很聪明，而且很努力。", "wp": "ér", "pp": "ér qiě", "sp": "tā hěn cōng míng ， ér qiě hěn nǔ lì 。"},
  { "w": "过", "p": "过去", "s": "时间过得真快。", "wp": "guò", "pp": "guò qù", "sp": "shí jiān guò dé zhēn kuài 。"},
  { "w": "着", "p": "看着", "s": "我看着小鸟在天上飞。", "wp": "zhuó", "pp": "kàn zhuó", "sp": "wǒ kàn zhuó xiǎo niǎo zài tiān shàng fēi 。"},
  { "w": "想", "p": "想法", "s": "我想吃苹果。", "wp": "xiǎng", "pp": "xiǎng fǎ", "sp": "wǒ xiǎng chī pín guǒ 。"},
  { "w": "都", "p": "都是", "s": "我们都是好朋友。", "wp": "dū", "pp": "dū shì", "sp": "wǒ men dū shì hǎo péng yǒu 。"},
  { "w": "把", "p": "把手", "s": "请把手举起来。", "wp": "bǎ", "pp": "bǎ shǒu", "sp": "qǐng bǎ shǒu jǔ qǐ lái 。"},
  { "w": "用", "p": "用力", "s": "我用力地拍了一下球。", "wp": "yòng", "pp": "yòng lì", "sp": "wǒ yòng lì dì pāi le yī xià qiú 。"},
  { "w": "但", "p": "但是", "s": "今天很热，但是我想喝热水。", "wp": "dàn", "pp": "dàn shì", "sp": "jīn tiān hěn rè ， dàn shì wǒ xiǎng hē rè shuǐ 。"},
  { "w": "于", "p": "对于", "s": "对于这个问题，我不知道怎么回答。", "wp": "yú", "pp": "duì yú", "sp": "duì yú zhè gè wèn tí ， wǒ bù zhī dào zěn me huí dá 。"},
  { "w": "种", "p": "种花", "s": "我在家里种了很多花。", "wp": "zhǒng", "pp": "zhòng huā", "sp": "wǒ zài jiā lǐ zhǒng le hěn duō huā 。"},
  { "w": "情", "p": "心情", "s": "我今天心情很好。", "wp": "qíng", "pp": "xīn qíng", "sp": "wǒ jīn tiān xīn qíng hěn hǎo 。"},
  { "w": "意", "p": "意思", "s": "这个词是什么意思？", "wp": "yì", "pp": "yì sī", "sp": "zhè gè cí shì shén me yì sī ？"},
  { "w": "方", "p": "方向", "s": "他指明了前进的方向。", "wp": "fāng", "pp": "fāng xiàng", "sp": "tā zhǐ míng liǎo qián jìn de fāng xiàng 。"},
  { "w": "法", "p": "方法", "s": "这是一个好方法。", "wp": "fǎ", "pp": "fāng fǎ", "sp": "zhè shì yī gè hǎo fāng fǎ 。"},
  { "w": "知", "p": "知道", "s": "我知道他叫什么名字。", "wp": "zhī", "pp": "zhī dào", "sp": "wǒ zhī dào tā jiào shén me míng zì 。"},
  { "w": "世", "p": "世界", "s": "世界很大，我想去看看。", "wp": "shì", "pp": "shì jiè", "sp": "shì jiè hěn dà ， wǒ xiǎng qù kàn kàn 。"},
  { "w": "两", "p": "两天", "s": "我想请两天假。", "wp": "liǎng", "pp": "liǎng tiān", "sp": "wǒ xiǎng qǐng liǎng tiān jiǎ 。"},
  { "w": "次", "p": "一次", "s": "这次考试很难。", "wp": "cì", "pp": "yī cì", "sp": "zhè cì kǎo shì hěn nán 。"},
  { "w": "使", "p": "使用", "s": "请使用这支笔写字。", "wp": "shǐ", "pp": "shǐ yòng", "sp": "qǐng shǐ yòng zhè zhī bǐ xiě zì 。"},
  { "w": "身", "p": "身体", "s": "他的身体很健康。", "wp": "shēn", "pp": "shēn tǐ", "sp": "tā de shēn tǐ hěn jiàn kāng 。"},
  { "w": "者", "p": "作者", "s": "这本书的作者是谁？", "wp": "zhě", "pp": "zuò zhě", "sp": "zhè běn shū de zuò zhě shì shuí ？"},
  { "w": "被", "p": "被子", "s": "我盖着被子睡觉。", "wp": "bèi", "pp": "bèi zǐ", "sp": "wǒ gài zhuó bèi zǐ shuì jiào 。"},
  { "w": "已", "p": "已经", "s": "我已经吃完饭了。", "wp": "yǐ", "pp": "yǐ jīng", "sp": "wǒ yǐ jīng chī wán fàn le 。"},
  { "w": "其", "p": "其中", "s": "其中一个苹果是红色的。", "wp": "qí", "pp": "qí zhōng", "sp": "qí zhōng yī gè pín guǒ shì hóng sè de 。"},
  { "w": "进", "p": "进来", "s": "请进房间。", "wp": "jìn", "pp": "jìn lái", "sp": "qǐng jìn fáng jiān 。"},
  { "w": "此", "p": "因此", "s": "因此，我们要好好学习。", "wp": "cǐ", "pp": "yīn cǐ", "sp": "yīn cǐ ， wǒ men yāo hǎo hào xué xí 。"},
  { "w": "话", "p": "说话", "s": "我们要好好说话。", "wp": "huà", "pp": "shuō huà", "sp": "wǒ men yāo hǎo hǎo shuō huà 。"},
  { "w": "常", "p": "常常", "s": "他常常去公园玩。", "wp": "cháng", "pp": "cháng cháng", "sp": "tā cháng cháng qù gōng yuán wán 。"},
  { "w": "与", "p": "与其", "s": "与其在家，不如出去玩。", "wp": "yǔ", "pp": "yǔ qí", "sp": "yǔ qí zài jiā ， bù rú chū qù wán 。"},
  { "w": "活", "p": "生活", "s": "我们要好好生活。", "wp": "huó", "pp": "shēng huó", "sp": "wǒ men yāo hǎo hǎo shēng huó 。"},
  { "w": "正", "p": "正好", "s": "我正好有十块钱。", "wp": "zhèng", "pp": "zhèng hǎo", "sp": "wǒ zhèng hǎo yǒu shí kuài qián 。"},
  { "w": "感", "p": "感觉", "s": "我感觉很冷。", "wp": "gǎn", "pp": "gǎn jué", "sp": "wǒ gǎn jué hěn lěng 。"},
  { "w": "明", "p": "明天", "s": "明天是星期天。", "wp": "míng", "pp": "míng tiān", "sp": "míng tiān shì xīng qī tiān 。"},
  { "w": "力", "p": "力气", "s": "他很有力气。", "wp": "lì", "pp": "lì qì", "sp": "tā hěn yǒu lì qì 。"},
  { "w": "理", "p": "理解", "s": "我理解你的意思。", "wp": "lǐ", "pp": "lǐ jiě", "sp": "wǒ lǐ jiě nǐ de yì sī 。"},
  { "w": "点", "p": "点心", "s": "我想吃点心。", "wp": "diǎn", "pp": "diǎn xīn", "sp": "wǒ xiǎng chī diǎn xīn 。"},
  { "w": "定", "p": "一定", "s": "我一定要考好。", "wp": "dìng", "pp": "yī dìng", "sp": "wǒ yī dìng yào kǎo hǎo 。"},
  { "w": "本", "p": "本子", "s": "我有一个新本子。", "wp": "běn", "pp": "běn zǐ", "sp": "wǒ yǒu yī gè xīn běn zǐ 。"},
  { "w": "公", "p": "公园", "s": "我喜欢去公园玩。", "wp": "gōng", "pp": "gōng yuán", "sp": "wǒ xǐ huān qù gōng yuán wán 。"},
  { "w": "特", "p": "特别", "s": "这个苹果特别甜。", "wp": "tè", "pp": "tè bié", "sp": "zhè gè pín guǒ tè bié tián 。"},
  { "w": "相", "p": "相信", "s": "我相信你。", "wp": "xiāng", "pp": "xiāng xìn", "sp": "wǒ xiāng xìn nǐ 。"},
  { "w": "将", "p": "将来", "s": "将来我想当一名老师。", "wp": "jiāng", "pp": "jiāng lái", "sp": "jiāng lái wǒ xiǎng dāng yī míng lǎo shī 。"},
  { "w": "实", "p": "实在", "s": "他很实在。", "wp": "shí", "pp": "shí zài", "sp": "tā hěn shí zài 。"},
  { "w": "向", "p": "方向", "s": "他走向了学校。", "wp": "xiàng", "pp": "fāng xiàng", "sp": "tā zǒu xiàng le xué xiào 。"},
  { "w": "声", "p": "声音", "s": "我听到了他的声音。", "wp": "shēng", "pp": "shēng yīn", "sp": "wǒ tīng dào le tā de shēng yīn 。"},
  { "w": "车", "p": "车子", "s": "我家有一辆车子。", "wp": "chē", "pp": "chē zǐ", "sp": "wǒ jiā yǒu yī liàng chē zǐ 。"},
  { "w": "全", "p": "全部", "s": "我们全部都通过了考试。", "wp": "quán", "pp": "quán bù", "sp": "wǒ men quán bù dū tōng guò le kǎo shì 。"},
  { "w": "信", "p": "相信", "s": "我相信他会来的。", "wp": "xìn", "pp": "xiāng xìn", "sp": "wǒ xiāng xìn tā huì lái de 。"},
  { "w": "重", "p": "重要", "s": "这很重要。", "wp": "zhòng", "pp": "zhòng yào", "sp": "zhè hěn zhòng yào 。"},
  { "w": "三", "p": "三个", "s": "我有三个苹果。", "wp": "sān", "pp": "sān gè", "sp": "wǒ yǒu sān gè pín guǒ 。"},
  { "w": "机", "p": "机会", "s": "这是一个好机会。", "wp": "jī", "pp": "jī huì", "sp": "zhè shì yī gè hǎo jī huì 。"},
  { "w": "物", "p": "礼物", "s": "这是我送给你的礼物。", "wp": "wù", "pp": "lǐ wù", "sp": "zhè shì wǒ sòng gěi nǐ de lǐ wù 。"},
  { "w": "气", "p": "生气", "s": "他生气了。", "wp": "qì", "pp": "shēng qì", "sp": "tā shēng qì le 。"},
  { "w": "每", "p": "每天", "s": "我每天都去上学。", "wp": "měi", "pp": "měi tiān", "sp": "wǒ měi tiān dū qù shàng xué 。"},
  { "w": "并", "p": "并且", "s": "他很聪明，并且很努力。", "wp": "bìng", "pp": "bìng qiě", "sp": "tā hěn cōng míng ， bìng qiě hěn nǔ lì 。"},
  { "w": "真", "p": "真的", "s": "这是真的吗？", "wp": "zhēn", "pp": "zhēn de", "sp": "zhè shì zhēn de ma ？"},
  { "w": "太", "p": "太太", "s": "这太好吃了！", "wp": "tài", "pp": "tài tài", "sp": "zhè tài hǎo chī le ！"},
  { "w": "新", "p": "新的", "s": "我有一个新的书包。", "wp": "xīn", "pp": "xīn de", "sp": "wǒ yǒu yī gè xīn de shū bāo 。"},
  { "w": "比", "p": "比较", "s": "这两个苹果比较大。", "wp": "bǐ", "pp": "bǐ jiào", "sp": "zhè liǎng gè pín guǒ bǐ jiào dà 。"},
  { "w": "便", "p": "方便", "s": "这个很方便。", "wp": "biàn", "pp": "fāng biàn", "sp": "zhè gè hěn fāng biàn 。"},
  { "w": "再", "p": "再见", "s": "我们再见！", "wp": "zài", "pp": "zài jiàn", "sp": "wǒ men zài jiàn ！"},
  { "w": "部", "p": "部分", "s": "这本书的部分内容很有趣。", "wp": "bù", "pp": "bù fèn", "sp": "zhè běn shū de bù fèn nèi róng hěn yǒu qù 。"},
  { "w": "像", "p": "好像", "s": "他好像很高兴。", "wp": "xiàng", "pp": "hǎo xiàng", "sp": "tā hǎo xiàng hěn gāo xìng 。"},
  { "w": "等", "p": "等等", "s": "我喜欢吃苹果、香蕉等等。", "wp": "děng", "pp": "děng děng", "sp": "wǒ xǐ huān chī pín guǒ 、 xiāng jiāo děng děng 。"},
  { "w": "体", "p": "身体", "s": "身体健康很重要。", "wp": "tǐ", "pp": "shēn tǐ", "sp": "shēn tǐ jiàn kāng hěn zhòng yào 。"},
  { "w": "却", "p": "却说", "s": "他却说他不知道。", "wp": "què", "pp": "què shuō", "sp": "tā què shuō tā bù zhī dào 。"},
  { "w": "电", "p": "电话", "s": "我想打电话。", "wp": "diàn", "pp": "diàn huà", "sp": "wǒ xiǎng dǎ diàn huà 。"},
  { "w": "界", "p": "世界", "s": "世界很大。", "wp": "jiè", "pp": "shì jiè", "sp": "shì jiè hěn dà 。"},
  { "w": "门", "p": "门口", "s": "我站在门口等你。", "wp": "mén", "pp": "mén kǒu", "sp": "wǒ zhàn zài mén kǒu děng nǐ 。"},
  { "w": "利", "p": "利用", "s": "我们要好好利用时间。", "wp": "lì", "pp": "lì yòng", "sp": "wǒ men yāo hǎo hǎo lì yòng shí jiān 。"},
  { "w": "海", "p": "海边", "s": "我喜欢去海边玩。", "wp": "hǎi", "pp": "hǎi biān", "sp": "wǒ xǐ huān qù hǎi biān wán 。"},
  { "w": "受", "p": "受到", "s": "他受到了表扬。", "wp": "shòu", "pp": "shòu dào", "sp": "tā shòu dào le biǎo yáng 。"},
  { "w": "表", "p": "表达", "s": "他表达了他的想法。", "wp": "biǎo", "pp": "biǎo dá", "sp": "tā biǎo dá le tā de xiǎng fǎ 。"},
  { "w": "德", "p": "道德", "s": "我们要讲道德。", "wp": "dé", "pp": "dào dé", "sp": "wǒ men yào jiǎng dào dé 。"},
  { "w": "克", "p": "克服", "s": "我们要克服困难。", "wp": "kè", "pp": "kè fú", "sp": "wǒ men yào kè fú kùn nán 。"},
  { "w": "代", "p": "代表", "s": "他代表我们班参加比赛。", "wp": "dài", "pp": "dài biǎo", "sp": "tā dài biǎo wǒ men bān cān jiā bǐ sài 。"},
  { "w": "员", "p": "队员", "s": "他是我们的队员。", "wp": "yuán", "pp": "duì yuán", "sp": "tā shì wǒ men de duì yuán 。"},
  { "w": "许", "p": "许多", "s": "有许多人喜欢他。", "wp": "xǔ", "pp": "xǔ duō", "sp": "yǒu xǔ duō rén xǐ huān tā 。"},
  { "w": "由", "p": "由于", "s": "由于生病，他没有去上学。", "wp": "yóu", "pp": "yóu yú", "sp": "yóu yú shēng bìng ， tā méi yǒu qù shàng xué 。"},
  { "w": "死", "p": "死亡", "s": "他生病去世了。", "wp": "sǐ", "pp": "sǐ wáng", "sp": "tā shēng bìng qù shì le 。"},
  { "w": "安", "p": "安全", "s": "安全很重要。", "wp": "ān", "pp": "ān quán", "sp": "ān quán hěn zhòng yào 。"},
  { "w": "性", "p": "性格", "s": "他的性格很好。", "wp": "xìng", "pp": "xìng gé", "sp": "tā de xìng gé hěn hǎo 。"},
  { "w": "光", "p": "阳光", "s": "阳光很温暖。", "wp": "guāng", "pp": "yáng guāng", "sp": "yáng guāng hěn wēn nuǎn 。"},
  { "w": "或", "p": "或者", "s": "你想吃苹果或者香蕉？", "wp": "huò", "pp": "huò zhě", "sp": "nǐ xiǎng chī pín guǒ huò zhě xiāng jiāo ？"},
  { "w": "住", "p": "住在", "s": "我住在北京。", "wp": "zhù", "pp": "zhù zài", "sp": "wǒ zhù zài běi jīng 。"},
  { "w": "难", "p": "难过", "s": "我很难过。", "wp": "nán", "pp": "nán guò", "sp": "wǒ hěn nán guò 。"},
  { "w": "望", "p": "希望", "s": "我希望你能来。", "wp": "wàng", "pp": "xī wàng", "sp": "wǒ xī wàng nǐ néng lái 。"},
  { "w": "教", "p": "教师", "s": "他是一名教师。", "wp": "jiào", "pp": "jiào shī", "sp": "tā shì yī míng jiào shī 。"},
  { "w": "命", "p": "生命", "s": "生命很宝贵。", "wp": "mìng", "pp": "shēng mìng", "sp": "shēng mìng hěn bǎo guì 。"},
  { "w": "结", "p": "结果", "s": "结果出来了。", "wp": "jié", "pp": "jié guǒ", "sp": "jié guǒ chū lái le 。"},
  { "w": "更", "p": "更加", "s": "他更加努力了。", "wp": "gēng", "pp": "gèng jiā", "sp": "tā gèng jiā nǔ lì le 。"},
  { "w": "拉", "p": "拉手", "s": "我们拉手吧。", "wp": "lā", "pp": "lā shǒu", "sp": "wǒ men lā shǒu bā 。"},
  { "w": "神", "p": "神奇", "s": "这太神奇了！", "wp": "shén", "pp": "shén qí", "sp": "zhè tài shén qí le ！"},
  { "w": "记", "p": "记得", "s": "我记得你。", "wp": "jì", "pp": "jì de", "sp": "wǒ jì de nǐ 。"},
  { "w": "让", "p": "让开", "s": "请让开一下。", "wp": "ràng", "pp": "ràng kāi", "sp": "qǐng ràng kāi yī xià 。"},
  { "w": "事", "p": "事情", "s": "今天学校里发生了一件有趣的事。", "wp": "shì", "pp": "shì qíng", "sp": "jīn tiān xué xiào lǐ fā shēng le yī jiàn yǒu qù de shì 。"},
  { "w": "书", "p": "书本", "s": "我喜欢看书本里的故事。", "wp": "shū", "pp": "shū běn", "sp": "wǒ xǐ huān kàn shū běn lǐ de gù shì 。"},
  { "w": "车", "p": "汽车", "s": "爸爸开着汽车带我去公园。", "wp": "chē", "pp": "qì chē", "sp": "bà bà kāi zhuó qì chē dài wǒ qù gōng yuán 。"},
  { "w": "动", "p": "动物", "s": "动物园里有各种各样的动物。", "wp": "dòng", "pp": "dòng wù", "sp": "dòng wù yuán lǐ yǒu gè zhǒng gè yàng de dòng wù 。"},
  { "w": "每", "p": "每天", "s": "我每天都按时上学。", "wp": "měi", "pp": "měi tiān", "sp": "wǒ měi tiān dū àn shí shàng xué 。"},
  { "w": "里", "p": "这里", "s": "这里是我的家。", "wp": "lǐ", "pp": "zhè lǐ", "sp": "zhè lǐ shì wǒ de jiā 。"},
  { "w": "进", "p": "进来", "s": "请进到房间里来。", "wp": "jìn", "pp": "jìn lái", "sp": "qǐng jìn dào fáng jiān lǐ lái 。"},
  { "w": "思", "p": "思考", "s": "我要好好思考这个问题。", "wp": "sī", "pp": "sī kǎo", "sp": "wǒ yāo hǎo hǎo sī kǎo zhè gè wèn tí 。"},
  { "w": "树", "p": "树木", "s": "公园里有很多高大的树木。", "wp": "shù", "pp": "shù mù", "sp": "gōng yuán lǐ yǒu hěn duō gāo dà de shù mù 。"},
  { "w": "水", "p": "水果", "s": "我喜欢吃各种各样的水果。", "wp": "shuǐ", "pp": "shuǐ guǒ", "sp": "wǒ xǐ huān chī gè zhǒng gè yàng de shuǐ guǒ 。"},
  { "w": "长", "p": "长短", "s": "这条绳子很长，那条绳子很短。", "wp": "cháng", "pp": "cháng duǎn", "sp": "zhè tiáo shéng zǐ hěn cháng ， nà tiáo shéng zǐ hěn duǎn 。"},
  { "w": "步", "p": "跑步", "s": "我每天早上都去跑步。", "wp": "bù", "pp": "pǎo bù", "sp": "wǒ měi tiān zǎo shàng dū qù pǎo bù 。"},
  { "w": "头", "p": "头顶", "s": "我的头顶上有一顶帽子。", "wp": "tóu", "pp": "tóu dǐng", "sp": "wǒ de tóu dǐng shàng yǒu yī dǐng mào zǐ 。"},
  { "w": "地", "p": "地方", "s": "我喜欢去美丽的地方玩。", "wp": "dì", "pp": "dì fāng", "sp": "wǒ xǐ huān qù měi lì de dì fāng wán 。"},
  { "w": "云", "p": "白云", "s": "天上飘着朵朵白云。", "wp": "yún", "pp": "bái yún", "sp": "tiān shàng piāo zhuó duǒ duǒ bái yún 。"},
  { "w": "加", "p": "加法", "s": "我正在学习加法运算。", "wp": "jiā", "pp": "jiā fǎ", "sp": "wǒ zhèng zài xué xí jiā fǎ yùn suàn 。"},
  { "w": "打", "p": "打球", "s": "我们一起去打球吧。", "wp": "dǎ", "pp": "dǎ qiú", "sp": "wǒ men yī qǐ qù dǎ qiú bā 。"},
  { "w": "远", "p": "远方", "s": "远方传来一阵美妙的歌声。", "wp": "yuǎn", "pp": "yuǎn fāng", "sp": "yuǎn fāng chuán lái yī zhèn měi miào de gē shēng 。"},
  { "w": "望", "p": "希望", "s": "我希望明天是个好天气。", "wp": "wàng", "pp": "xī wàng", "sp": "wǒ xī wàng míng tiān shì gè hǎo tiān qì 。"},
  { "w": "近", "p": "近处", "s": "我家就在学校附近。", "wp": "jìn", "pp": "jìn chù", "sp": "wǒ jiā jiù zài xué xiào fù jìn 。"},
  { "w": "走", "p": "走路", "s": "我每天走路上学。", "wp": "zǒu", "pp": "zǒu lù", "sp": "wǒ měi tiān zǒu lù shàng xué 。"},
  { "w": "向", "p": "方向", "s": "我朝着家的方向走去。", "wp": "xiàng", "pp": "fāng xiàng", "sp": "wǒ cháo zhe jiā de fāng xiàng zǒu qù 。"},
  { "w": "黑", "p": "黑色", "s": "我喜欢穿黑色的衣服。", "wp": "hēi", "pp": "hēi sè", "sp": "wǒ xǐ huān chuān hēi sè de yī fú 。"},
  { "w": "白", "p": "白色", "s": "天上的云朵是白色的。", "wp": "bái", "pp": "bái sè", "sp": "tiān shàng de yún duǒ shì bái sè de 。"},
  { "w": "开", "p": "开门", "s": "我打开门走了出去。", "wp": "kāi", "pp": "kāi mén", "sp": "wǒ dǎ kāi mén zǒu le chū qù 。"},
  { "w": "达", "p": "到达", "s": "我们终于到达了目的地。", "wp": "dá", "pp": "dào dá", "sp": "wǒ men zhōng yú dào dá le mù dì dì 。"},
  { "w": "办", "p": "办法", "s": "我想到了一个好办法。", "wp": "bàn", "pp": "bàn fǎ", "sp": "wǒ xiǎng dào le yī gè hǎo bàn fǎ 。"},
  { "w": "说", "p": "说话", "s": "我和朋友们一起说笑。", "wp": "shuō", "pp": "shuō huà", "sp": "wǒ hé péng yǒu mén yī qǐ shuō xiào 。"},
  { "w": "情", "p": "事情", "s": "这件事情很重要。", "wp": "qíng", "pp": "shì qíng", "sp": "zhè jiàn shì qíng hěn zhòng yào 。"},
  { "w": "光", "p": "光明", "s": "我们要追求光明。", "wp": "guāng", "pp": "guāng míng", "sp": "wǒ men yào zhuī qiú guāng míng 。"},
  { "w": "国", "p": "国家", "s": "我爱我的国家。", "wp": "guó", "pp": "guó jiā", "sp": "wǒ ài wǒ de guó jiā 。"},
  { "w": "系", "p": "联系", "s": "我和我的好朋友经常联系。", "wp": "xì", "pp": "lián xì", "sp": "wǒ hé wǒ de hǎo péng yǒu jīng cháng lián xì 。"},
  { "w": "以", "p": "以后", "s": "以后我要更加努力学习。", "wp": "yǐ", "pp": "yǐ hòu", "sp": "yǐ hòu wǒ yào gèng jiā nǔ lì xué xí 。"},
  { "w": "手", "p": "手指", "s": "我的手指很灵活。", "wp": "shǒu", "pp": "shǒu zhǐ", "sp": "wǒ de shǒu zhǐ hěn líng huó 。"},
  { "w": "代", "p": "代替", "s": "我代替妈妈去买东西。", "wp": "dài", "pp": "dài tì", "sp": "wǒ dài tì mā mā qù mǎi dōng xī 。"},
  { "w": "非", "p": "非常", "s": "他非常聪明。", "wp": "fēi", "pp": "fēi cháng", "sp": "tā fēi cháng cōng míng 。"},
  { "w": "听", "p": "听见", "s": "我听见小鸟在唱歌。", "wp": "tīng", "pp": "tīng jiàn", "sp": "wǒ tīng jiàn xiǎo niǎo zài chàng gē 。"},
  { "w": "动", "p": "运动", "s": "我喜欢做运动。", "wp": "dòng", "pp": "yùn dòng", "sp": "wǒ xǐ huān zuò yùn dòng 。"},
  { "w": "新", "p": "新年", "s": "新年到了，我们真高兴。", "wp": "xīn", "pp": "xīn nián", "sp": "xīn nián dào le ， wǒ men zhēn gāo xìng 。"},
  { "w": "重", "p": "重要", "s": "这件事情非常重要。", "wp": "zhòng", "pp": "zhòng yào", "sp": "zhè jiàn shì qíng fēi cháng zhòng yào 。"},
  { "w": "谈", "p": "谈话", "s": "我们谈论着有趣的事情。", "wp": "tán", "pp": "tán huà", "sp": "wǒ men tán lùn zhuó yǒu qù de shì qíng 。"},
  { "w": "学", "p": "学校", "s": "我在学校里学习知识。", "wp": "xué", "pp": "xué xiào", "sp": "wǒ zài xué xiào lǐ xué xí zhī shí 。"},
  { "w": "最", "p": "最近", "s": "我最近很忙。", "wp": "zuì", "pp": "zuì jìn", "sp": "wǒ zuì jìn hěn máng 。"},
  { "w": "放", "p": "放心", "s": "妈妈对我说：“你放心去吧。”", "wp": "fàng", "pp": "fàng xīn", "sp": "mā mā duì wǒ shuō ：“ nǐ fàng xīn qù bā 。”"},
  { "w": "人", "p": "人们", "s": "人们都在公园里玩耍。", "wp": "rén", "pp": "rén mén", "sp": "rén mén dū zài gōng yuán lǐ wán shuǎ 。"},
  { "w": "哪", "p": "哪里", "s": "你想去哪里玩？", "wp": "nǎ", "pp": "nǎ lǐ", "sp": "nǐ xiǎng qù nǎ lǐ wán ？"},
  { "w": "场", "p": "场地", "s": "学校的操场很大。", "wp": "cháng", "pp": "chǎng dì", "sp": "xué xiào de cāo chǎng hěn dà 。"},
  { "w": "黄", "p": "黄色", "s": "我喜欢黄色的花。", "wp": "huáng", "pp": "huáng sè", "sp": "wǒ xǐ huān huáng sè de huā 。"},
  { "w": "思", "p": "思想", "s": "我有自己的思想。", "wp": "sī", "pp": "sī xiǎng", "sp": "wǒ yǒu zì jǐ de sī xiǎng 。"},
  { "w": "好", "p": "好处", "s": "多读书有很多好处。", "wp": "hǎo", "pp": "hǎo chù", "sp": "duō dú shū yǒu hěn duō hǎo chù 。"},
  { "w": "管", "p": "管理", "s": "老师管理着班级。", "wp": "guǎn", "pp": "guǎn lǐ", "sp": "lǎo shī guǎn lǐ zhuó bān jí 。"},
  { "w": "自", "p": "自己", "s": "我自己的事情自己做。", "wp": "zì", "pp": "zì jǐ", "sp": "wǒ zì jǐ de shì qíng zì jǐ zuò 。"},
  { "w": "修", "p": "修理", "s": "我学会了修理自行车。", "wp": "xiū", "pp": "xiū lǐ", "sp": "wǒ xué huì le xiū lǐ zì xíng chē 。"},
  { "w": "住", "p": "居住", "s": "我居住在一个小城市里。", "wp": "zhù", "pp": "jū zhù", "sp": "wǒ jū zhù zài yī gè xiǎo chéng shì lǐ 。"},
  { "w": "付", "p": "付钱", "s": "我付了钱买了一本书。", "wp": "fù", "pp": "fù qián", "sp": "wǒ fù le qián mǎi le yī běn shū 。"},
  { "w": "派", "p": "派人", "s": "老师派人去参加比赛。", "wp": "pài", "pp": "pài rén", "sp": "lǎo shī pài rén qù cān jiā bǐ sài 。"},
  { "w": "简", "p": "简单", "s": "这个问题很简单。", "wp": "jiǎn", "pp": "jiǎn dān", "sp": "zhè gè wèn tí hěn jiǎn dān 。"},
  { "w": "提", "p": "提高", "s": "我要努力提高我的学习成绩。", "wp": "tí", "pp": "tí gāo", "sp": "wǒ yào nǔ lì tí gāo wǒ de xué xí chéng jì 。"},
  { "w": "有", "p": "有趣", "s": "这是一个有趣的故事。", "wp": "yǒu", "pp": "yǒu qù", "sp": "zhè shì yī gè yǒu qù de gù shì 。"},
  { "w": "记", "p": "记得", "s": "我记得昨天发生的事情。", "wp": "jì", "pp": "jì de", "sp": "wǒ jì de zuó tiān fā shēng de shì qíng 。"},
  { "w": "明", "p": "明天", "s": "明天我们要去春游。", "wp": "míng", "pp": "míng tiān", "sp": "míng tiān wǒ men yào qù chūn yóu 。"},
  { "w": "类", "p": "类别", "s": "这些书的类别不同。", "wp": "lèi", "pp": "lèi bié", "sp": "zhèi xiē shū de lèi bié bù tóng 。"},
  { "w": "多", "p": "多少", "s": "你有多少支铅笔？", "wp": "duō", "pp": "duō shǎo", "sp": "nǐ yǒu duō shǎo zhī qiān bǐ ？"},
  { "w": "当", "p": "当时", "s": "当时我正在看电视。", "wp": "dāng", "pp": "dāng shí", "sp": "dāng shí wǒ zhèng zài kàn diàn shì 。"},
  { "w": "声", "p": "声音", "s": "我听到了清脆的铃声。", "wp": "shēng", "pp": "shēng yīn", "sp": "wǒ tīng dào le qīng cuì de líng shēng 。"},
  { "w": "每", "p": "每次", "s": "我每次考试都很认真。", "wp": "měi", "pp": "měi cì", "sp": "wǒ měi cì kǎo shì dū hěn rèn zhēn 。"},
  { "w": "处", "p": "到处", "s": "公园里到处都是鲜花。", "wp": "chǔ", "pp": "dào chù", "sp": "gōng yuán lǐ dào chù dū shì xiān huā 。"},
  { "w": "现", "p": "现在", "s": "现在是下午三点。", "wp": "xiàn", "pp": "xiàn zài", "sp": "xiàn zài shì xià wǔ sān diǎn 。"},
  { "w": "否", "p": "是否", "s": "你是否愿意帮助我？", "wp": "fǒu", "pp": "shì fǒu", "sp": "nǐ shì fǒu yuàn yì bāng zhù wǒ ？"},
  { "w": "产", "p": "产品", "s": "这是一种新产品。", "wp": "chǎn", "pp": "chǎn pǐn", "sp": "zhè shì yī zhǒng xīn chǎn pǐn 。"},
  { "w": "街", "p": "街道", "s": "街道上车水马龙。", "wp": "jiē", "pp": "jiē dào", "sp": "jiē dào shàng chē shuǐ mǎ lóng 。"},
  { "w": "改", "p": "改变", "s": "我想改变我的坏习惯。", "wp": "gǎi", "pp": "gǎi biàn", "sp": "wǒ xiǎng gǎi biàn wǒ de huài xí guàn 。"},
  { "w": "弟", "p": "弟弟", "s": "我的弟弟很可爱。", "wp": "dì", "pp": "dì di", "sp": "wǒ de dì di hěn kě ài 。"},
  { "w": "是", "p": "是否", "s": "你是否喜欢吃苹果？", "wp": "shì", "pp": "shì fǒu", "sp": "nǐ shì fǒu xǐ huān chī pín guǒ ？"},
  { "w": "材", "p": "材料", "s": "这件衣服的材料很好。", "wp": "cái", "pp": "cái liào", "sp": "zhè jiàn yī fú de cái liào hěn hǎo 。"},
  { "w": "快", "p": "快乐", "s": "我祝你生日快乐！", "wp": "kuài", "pp": "kuài lè", "sp": "wǒ zhù nǐ shēng rì kuài lè ！"},
  { "w": "心", "p": "心情", "s": "我今天心情很好。", "wp": "xīn", "pp": "xīn qíng", "sp": "wǒ jīn tiān xīn qíng hěn hǎo 。"},
  { "w": "衣", "p": "衣服", "s": "我穿了一件新衣服。", "wp": "yī", "pp": "yī fú", "sp": "wǒ chuān le yī jiàn xīn yī fú 。"},
  { "w": "合", "p": "合适", "s": "这件衣服很合适你。", "wp": "hé", "pp": "hé shì", "sp": "zhè jiàn yī fú hěn hé shì nǐ 。"},
  { "w": "对", "p": "对错", "s": "你要分清对错。", "wp": "duì", "pp": "duì cuò", "sp": "nǐ yào fēn qīng duì cuò 。"},
  { "w": "书", "p": "书店", "s": "我去书店买书。", "wp": "shū", "pp": "shū diàn", "sp": "wǒ qù shū diàn mǎi shū 。"},
  { "w": "买", "p": "买菜", "s": "我去超市买东西。", "wp": "mǎi", "pp": "mǎi cài", "sp": "wǒ qù chāo shì mǎi dōng xī 。"},
  { "w": "发", "p": "发现", "s": "我发现了一个秘密。", "wp": "fā", "pp": "fā xiàn", "sp": "wǒ fā xiàn le yī gè mì mì 。"},
  { "w": "投", "p": "投篮", "s": "我投篮投进了。", "wp": "tóu", "pp": "tóu lán", "sp": "wǒ tóu lán tóu jìn le 。"},
  { "w": "希", "p": "希望", "s": "我希望你能考上大学。", "wp": "xī", "pp": "xī wàng", "sp": "wǒ xī wàng nǐ néng kǎo shàng dà xué 。"},
  { "w": "男", "p": "男孩", "s": "我是一个男孩。", "wp": "nán", "pp": "nán hái", "sp": "wǒ shì yī gè nán hái 。"},
  { "w": "进", "p": "进步", "s": "我的学习有进步。", "wp": "jìn", "pp": "jìn bù", "sp": "wǒ de xué xí yǒu jìn bù 。"},
  { "w": "防", "p": "防火", "s": "我们要做好防火工作。", "wp": "fáng", "pp": "fáng huǒ", "sp": "wǒ men yào zuò hǎo fáng huǒ gōng zuò 。"},
  { "w": "消", "p": "消失", "s": "他消失在人群中。", "wp": "xiāo", "pp": "xiāo shī", "sp": "tā xiāo shī zài rén qún zhōng 。"},
  { "w": "电", "p": "电脑", "s": "我喜欢玩电脑游戏。", "wp": "diàn", "pp": "diàn nǎo", "sp": "wǒ xǐ huān wán diàn nǎo yóu xì 。"},
  { "w": "留", "p": "留住", "s": "我们要留住美好的回忆。", "wp": "liú", "pp": "liú zhù", "sp": "wǒ men yào liú zhù měi hǎo de huí yì 。"},
  { "w": "化", "p": "变化", "s": "天气变化很快。", "wp": "huà", "pp": "biàn huà", "sp": "tiān qì biàn huà hěn kuài 。"},
  { "w": "港", "p": "香港", "s": "我想去香港旅游。", "wp": "gǎng", "pp": "xiāng gǎng", "sp": "wǒ xiǎng qù xiāng gǎng lǚ yóu 。"},
  { "w": "脚", "p": "脚步", "s": "我加快了脚步。", "wp": "jiǎo", "pp": "jiǎo bù", "sp": "wǒ jiā kuài le jiǎo bù 。"},
  { "w": "集", "p": "集合", "s": "我们在学校门口集合。", "wp": "jí", "pp": "jí hé", "sp": "wǒ men zài xué xiào mén kǒu jí hé 。"},
  { "w": "活", "p": "活动", "s": "学校组织了一次有趣的活动。", "wp": "huó", "pp": "huó dòng", "sp": "xué xiào zǔ zhī le yī cì yǒu qù de huó dòng 。"},
  { "w": "命", "p": "生命", "s": "生命是宝贵的。", "wp": "mìng", "pp": "shēng mìng", "sp": "shēng mìng shì bǎo guì de 。"},
  { "w": "秘", "p": "秘密", "s": "我有一个小秘密。", "wp": "mì", "pp": "mì mì", "sp": "wǒ yǒu yī gè xiǎo mì mì 。"},
  { "w": "病", "p": "生病", "s": "我生病了，要去医院看医生。", "wp": "bìng", "pp": "shēng bìng", "sp": "wǒ shēng bìng le ， yào qù yī yuàn kàn yī shēng 。"},
  { "w": "面", "p": "见面", "s": "我今天在学校门口见到了我的好朋友。", "wp": "miàn", "pp": "jiàn miàn", "sp": "wǒ jīn tiān zài xué xiào mén kǒu jiàn dào le wǒ de hǎo péng yǒu 。"},
  { "w": "经", "p": "经过", "s": "汽车经过了长长的隧道。", "wp": "jīng", "pp": "jīng guò", "sp": "qì chē jīng guò le cháng cháng de suì dào 。"},
  { "w": "总", "p": "总数", "s": "这次考试的总数是多少？", "wp": "zǒng", "pp": "zǒng shù", "sp": "zhè cì kǎo shì de zǒng shù shì duō shǎo ？"},
  { "w": "关", "p": "关心", "s": "妈妈很关心我的学习。", "wp": "guān", "pp": "guān xīn", "sp": "mā mā hěn guān xīn wǒ de xué xí 。"},
  { "w": "题", "p": "问题", "s": "这个问题我不会做。", "wp": "tí", "pp": "wèn tí", "sp": "zhè gè wèn tí wǒ bú huì zuò 。"},
  { "w": "度", "p": "程度", "s": "这件事情的严重程度超出了我的想象。", "wp": "dù", "pp": "chéng dù", "sp": "zhè jiàn shì qíng de yán zhòng chéng dù chāo chū le wǒ de xiǎng xiàng 。"},
  { "w": "位", "p": "位置", "s": "我的位置在教室的中间。", "wp": "wèi", "pp": "wèi zhì", "sp": "wǒ de wèi zhì zài jiào shì de zhōng jiān 。"},
  { "w": "完", "p": "完成", "s": "我完成了今天的作业。", "wp": "wán", "pp": "wán chéng", "sp": "wǒ wán chéng le jīn tiān de zuò yè 。"},
  { "w": "建", "p": "建议", "s": "我给你一个建议。", "wp": "jiàn", "pp": "jiàn yì", "sp": "wǒ gěi nǐ yī gè jiàn yì 。"},
  { "w": "议", "p": "议论", "s": "大家在议论这件事情。", "wp": "yì", "pp": "yì lùn", "sp": "dà jiā zài yì lùn zhè jiàn shì qíng 。"},
  { "w": "务", "p": "任务", "s": "我要完成老师布置的任务。", "wp": "wù", "pp": "rèn wù", "sp": "wǒ yào wán chéng lǎo shī bù zhì de rèn wù 。"},
  { "w": "平", "p": "平安", "s": "我希望你每天都平平安安的。", "wp": "píng", "pp": "píng ān", "sp": "wǒ xī wàng nǐ měi tiān dū píng píng ān ān de 。"},
  { "w": "报", "p": "报告", "s": "我向老师报告了这件事情。", "wp": "bào", "pp": "bào gào", "sp": "wǒ xiàng lǎo shī bào gào le zhè jiàn shì qíng 。"},
  { "w": "决", "p": "决定", "s": "我决定明天去公园玩。", "wp": "jué", "pp": "jué dìng", "sp": "wǒ jué dìng míng tiān qù gōng yuán wán 。"},
  { "w": "计", "p": "计划", "s": "我计划下个星期去北京旅游。", "wp": "jì", "pp": "jì huá", "sp": "wǒ jì huá xià gè xīng qī qù běi jīng lǚ yóu 。"},
  { "w": "术", "p": "技术", "s": "他的技术很棒。", "wp": "shù", "pp": "jì shù", "sp": "tā de jì shù hěn bàng 。"},
  { "w": "极", "p": "积极", "s": "我们要积极参加学校组织的活动。", "wp": "jí", "pp": "jī jí", "sp": "wǒ men yào jī jí cān jiā xué xiào zǔ zhī de huó dòng 。"},
  { "w": "收", "p": "收到", "s": "我收到了你的礼物。", "wp": "shōu", "pp": "shōu dào", "sp": "wǒ shōu dào le nǐ de lǐ wù 。"},
  { "w": "华", "p": "华丽", "s": "这件衣服很华丽。", "wp": "huá", "pp": "huá lì", "sp": "zhè jiàn yī fú hěn huá lì 。"},
  { "w": "联", "p": "联系", "s": "我和我的好朋友经常联系。", "wp": "lián", "pp": "lián xì", "sp": "wǒ hé wǒ de hǎo péng yǒu jīng cháng lián xì 。"},
  { "w": "资", "p": "资料", "s": "我在网上查找学习资料。", "wp": "zī", "pp": "zī liào", "sp": "wǒ zài wǎng shàng chá zhǎo xué xí zī liào 。"},
  { "w": "交", "p": "交通", "s": "现在的交通越来越便利了。", "wp": "jiāo", "pp": "jiāo tōng", "sp": "xiàn zài de jiāo tōng yuè lái yuè biàn lì le 。"},
  { "w": "任", "p": "任务", "s": "我要完成老师交给我的任务。", "wp": "rèn", "pp": "rèn wù", "sp": "wǒ yào wán chéng lǎo shī jiāo gěi wǒ de rèn wù 。"},
  { "w": "金", "p": "金色", "s": "我喜欢金色的阳光。", "wp": "jīn", "pp": "jīn sè", "sp": "wǒ xǐ huān jīn sè de yáng guāng 。"},
  { "w": "规", "p": "规定", "s": "我们要遵守学校的规定。", "wp": "guī", "pp": "guī dìng", "sp": "wǒ men yào zūn shǒu xué xiào de guī dìng 。"},
  { "w": "切", "p": "切开", "s": "我把苹果切开了。", "wp": "qiē", "pp": "qiē kāi", "sp": "wǒ bǎ pín guǒ qiē kāi le 。"},
  { "w": "直", "p": "直线", "s": "这条直线很长。", "wp": "zhí", "pp": "zhí xiàn", "sp": "zhè tiáo zhí xiàn hěn cháng 。"},
  { "w": "持", "p": "坚持", "s": "我们要坚持每天锻炼身体。", "wp": "chí", "pp": "jiān chí", "sp": "wǒ men yào jiān chí měi tiān duàn liàn shēn tǐ 。"},
  { "w": "始", "p": "开始", "s": "故事开始了。", "wp": "shǐ", "pp": "kāi shǐ", "sp": "gù shì kāi shǐ le 。"},
  { "w": "终", "p": "终于", "s": "我终于完成了我的梦想。", "wp": "zhōng", "pp": "zhōng yú", "sp": "wǒ zhōng yú wán chéng le wǒ de mèng xiǎng 。"},
  { "w": "必", "p": "必须", "s": "我们必须按时完成作业。", "wp": "bì", "pp": "bì xū", "sp": "wǒ men bì xū àn shí wán chéng zuò yè 。"},
  { "w": "深", "p": "深浅", "s": "这条河的深浅我不知道。", "wp": "shēn", "pp": "shēn qiǎn", "sp": "zhè tiáo hé de shēn qiǎn wǒ bù zhī dào 。"},
  { "w": "何", "p": "如何", "s": "你知道如何解决这个问题吗？", "wp": "hé", "pp": "rú hé", "sp": "nǐ zhī dào rú hé jiě jué zhè gè wèn tí ma ？"},
  { "w": "调", "p": "调查", "s": "我要调查一下这件事情。", "wp": "tiáo", "pp": "diào chá", "sp": "wǒ yào diào chá yī xià zhè jiàn shì qíng 。"},
  { "w": "证", "p": "证明", "s": "你有什么可以证明你说的是真的吗？", "wp": "zhèng", "pp": "zhèng míng", "sp": "nǐ yǒu shén me kě yǐ zhèng míng nǐ shuō de shì zhēn de ma ？"},
  { "w": "界", "p": "世界", "s": "世界很大，我想去看看。", "wp": "jiè", "pp": "shì jiè", "sp": "shì jiè hěn dà ， wǒ xiǎng qù kàn kàn 。"},
  { "w": "流", "p": "流水", "s": "河里的水在流淌。", "wp": "liú", "pp": "liú shuǐ", "sp": "hé lǐ de shuǐ zài liú tǎng 。"},
  { "w": "引", "p": "引导", "s": "老师引导我们学习知识。", "wp": "yǐn", "pp": "yǐn dǎo", "sp": "lǎo shī yǐn dǎo wǒ men xué xí zhī shí 。"},
  { "w": "严", "p": "严格", "s": "老师对我们要求很严格。", "wp": "yán", "pp": "yán gé", "sp": "lǎo shī duì wǒ men yāo qiú hěn yán gé 。"},
  { "w": "失", "p": "失去", "s": "我失去了我的铅笔。", "wp": "shī", "pp": "shī qù", "sp": "wǒ shī qù le wǒ de qiān bǐ 。"},
  { "w": "转", "p": "转身", "s": "他转过身对我说。", "wp": "zhuǎn", "pp": "zhuǎn shēn", "sp": "tā zhuǎn guò shēn duì wǒ shuō 。"},
  { "w": "份", "p": "一份", "s": "我吃了一份冰淇淋。", "wp": "fèn", "pp": "yī fèn", "sp": "wǒ chī le yī fèn bīng qí lín 。"},
  { "w": "准", "p": "准备", "s": "我正在准备考试。", "wp": "zhǔn", "pp": "zhǔn bèi", "sp": "wǒ zhèng zài zhǔn bèi kǎo shì 。"},
  { "w": "约", "p": "约定", "s": "我们约定明天一起去公园玩。", "wp": "yuē", "pp": "yuē dìng", "sp": "wǒ men yuē dìng míng tiān yī qǐ qù gōng yuán wán 。"},
  { "w": "注", "p": "注意", "s": "上课时我们要集中注意力。", "wp": "zhù", "pp": "zhù yì", "sp": "shàng kè shí wǒ men yào jí zhōng zhù yì lì 。"},
  { "w": "术", "p": "艺术", "s": "我喜欢学习艺术。", "wp": "shù", "pp": "yì shù", "sp": "wǒ xǐ huān xué xí yì shù 。"},
  { "w": "该", "p": "应该", "s": "我们应该帮助有困难的人。", "wp": "gāi", "pp": "yīng gāi", "sp": "wǒ men yīng gāi bāng zhù yǒu kùn nán de rén 。"},
  { "w": "论", "p": "讨论", "s": "我们一起讨论一下这个问题。", "wp": "lùn", "pp": "tǎo lùn", "sp": "wǒ men yī qǐ tǎo lùn yī xià zhè gè wèn tí 。"},
  { "w": "程", "p": "过程", "s": "学习是一个漫长的过程。", "wp": "chéng", "pp": "guò chéng", "sp": "xué xí shì yī gè màn cháng de guò chéng 。"},
  { "w": "争", "p": "争吵", "s": "他们因为一件小事争吵起来。", "wp": "zhēng", "pp": "zhēng chǎo", "sp": "tā mén yīn wèi yī jiàn xiǎo shì zhēng chǎo qǐ lái 。"},
  { "w": "究", "p": "研究", "s": "我要研究一下这个问题。", "wp": "jiū", "pp": "yán jiū", "sp": "wǒ yào yán jiū yī xià zhè gè wèn tí 。"},
  { "w": "精", "p": "精神", "s": "我们要有积极向上的精神。", "wp": "jīng", "pp": "jīng shén", "sp": "wǒ men yào yǒu jī jí xiàng shàng de jīng shén 。"},
  { "w": "断", "p": "断开", "s": "这根绳子断开了。", "wp": "duàn", "pp": "duàn kāi", "sp": "zhè gēn shéng zǐ duàn kāi le 。"},
  { "w": "权", "p": "权利", "s": "我们都有受教育的权利。", "wp": "quán", "pp": "quán lì", "sp": "wǒ men dū yǒu shòu jiào yù de quán lì 。"},
  { "w": "运", "p": "运动", "s": "我喜欢做运动。", "wp": "yùn", "pp": "yùn dòng", "sp": "wǒ xǐ huān zuò yùn dòng 。"},
  { "w": "历", "p": "历史", "s": "我对历史很感兴趣。", "wp": "lì", "pp": "lì shǐ", "sp": "wǒ duì lì shǐ hěn gǎn xìng qù 。"},
  { "w": "较", "p": "比较", "s": "这两个苹果比较大。", "wp": "jiào", "pp": "bǐ jiào", "sp": "zhè liǎng gè pín guǒ bǐ jiào dà 。"},
  { "w": "青", "p": "青色", "s": "我喜欢青色的衣服。", "wp": "qīng", "pp": "qīng sè", "sp": "wǒ xǐ huān qīng sè de yī fú 。"},
  { "w": "增", "p": "增加", "s": "我们要增加学习时间。", "wp": "zēng", "pp": "zēng jiā", "sp": "wǒ men yào zēng jiā xué xí shí jiān 。"},
  { "w": "案", "p": "答案", "s": "我找到了这个问题的答案。", "wp": "àn", "pp": "dá àn", "sp": "wǒ zhǎo dào le zhè gè wèn tí de dá àn 。"},
  { "w": "史", "p": "历史", "s": "我喜欢学习历史。", "wp": "shǐ", "pp": "lì shǐ", "sp": "wǒ xǐ huān xué xí lì shǐ 。"},
  { "w": "示", "p": "表示", "s": "他向我表示感谢。", "wp": "shì", "pp": "biǎo shì", "sp": "tā xiàng wǒ biǎo shì gǎn xiè 。"},
  { "w": "风", "p": "风雨", "s": "外面刮风下雨了。", "wp": "fēng", "pp": "fēng yǔ", "sp": "wài miàn guā fēng xià yǔ le 。"},
  { "w": "容", "p": "容易", "s": "这个问题很容易解决。", "wp": "róng", "pp": "róng yì", "sp": "zhè gè wèn tí hěn róng yì jiě jué 。"},
  { "w": "请", "p": "请求", "s": "我请求你帮助我。", "wp": "qǐng", "pp": "qǐng qiú", "sp": "wǒ qǐng qiú nǐ bāng zhù wǒ 。"},
  { "w": "底", "p": "底下", "s": "书桌底下有一本书。", "wp": "dǐ", "pp": "dǐ xià", "sp": "shū zhuō dǐ xià yǒu yī běn shū 。"},
  { "w": "存", "p": "存在", "s": "这个问题一直存在。", "wp": "cún", "pp": "cún zài", "sp": "zhè gè wèn tí yī zhí cún zài 。"},
  { "w": "整", "p": "整理", "s": "我正在整理房间。", "wp": "zhěng", "pp": "zhěng lǐ", "sp": "wǒ zhèng zài zhěng lǐ fáng jiān 。"},
  { "w": "支", "p": "支持", "s": "我支持你的决定。", "wp": "zhī", "pp": "zhī chí", "sp": "wǒ zhī chí nǐ de jué dìng 。"},
  { "w": "研", "p": "研究", "s": "我正在研究这个问题。", "wp": "yán", "pp": "yán jiū", "sp": "wǒ zhèng zài yán jiū zhè gè wèn tí 。"},
  { "w": "各", "p": "各自", "s": "我们各自回家。", "wp": "gè", "pp": "gè zì", "sp": "wǒ men gè zì huí jiā 。"},
  { "w": "划", "p": "计划", "s": "我计划明天去爬山。", "wp": "huá", "pp": "jì huá", "sp": "wǒ jì huá míng tiān qù pá shān 。"},
  { "w": "半", "p": "一半", "s": "我吃了一半苹果。", "wp": "bàn", "pp": "yī bàn", "sp": "wǒ chī le yī bàn pín guǒ 。"},
  { "w": "商", "p": "商量", "s": "我们商量一下这个问题。", "wp": "shāng", "pp": "shāng liáng", "sp": "wǒ men shāng liáng yī xià zhè gè wèn tí 。"},
  { "w": "格", "p": "格子", "s": "我喜欢穿格子衣服。", "wp": "gé", "pp": "gé zǐ", "sp": "wǒ xǐ huān chuān gé zǐ yī fú 。"},
  { "w": "般", "p": "一般", "s": "他长得很一般。", "wp": "bān", "pp": "yī bān", "sp": "tā cháng dé hěn yī bān 。"},
  { "w": "确", "p": "确定", "s": "我确定明天去上学。", "wp": "què", "pp": "què dìng", "sp": "wǒ què dìng míng tiān qù shàng xué 。"},
  { "w": "势", "p": "趋势", "s": "现在的趋势是越来越多人使用手机。", "wp": "shì", "pp": "qū shì", "sp": "xiàn zài de qū shì shì yuè lái yuè duō rén shǐ yòng shǒu jī 。"},
  { "w": "质", "p": "质量", "s": "这件衣服质量很好。", "wp": "zhì", "pp": "zhì liàng", "sp": "zhè jiàn yī fú zhì liàng hěn hǎo 。"},
  { "w": "变", "p": "变化", "s": "天气变化很快。", "wp": "biàn", "pp": "biàn huà", "sp": "tiān qì biàn huà hěn kuài 。"},
  { "w": "团", "p": "团结", "s": "我们要团结友爱。", "wp": "tuán", "pp": "tuán jié", "sp": "wǒ men yào tuán jié yǒu ài 。"},
  { "w": "线", "p": "线条", "s": "这幅画的线条很流畅。", "wp": "xiàn", "pp": "xiàn tiáo", "sp": "zhè fú huà de xiàn tiáo hěn liú chàng 。"},
  { "w": "果", "p": "水果", "s": "我喜欢吃水果。", "wp": "guǒ", "pp": "shuǐ guǒ", "sp": "wǒ xǐ huān chī shuǐ guǒ 。"},
  { "w": "族", "p": "民族", "s": "我是中国汉族人。", "wp": "zú", "pp": "mín zú", "sp": "wǒ shì zhōng guó hàn zú rén 。"},
  { "w": "丽", "p": "美丽", "s": "这里的风景很美丽。", "wp": "lì", "pp": "měi lì", "sp": "zhè lǐ de fēng jǐng hěn měi lì 。"},
  { "w": "客", "p": "客人", "s": "我家来了客人。", "wp": "kè", "pp": "kè rén", "sp": "wǒ jiā lái le kè rén 。"},
  { "w": "科", "p": "科学", "s": "我喜欢学习科学。", "wp": "kē", "pp": "kē xué", "sp": "wǒ xǐ huān xué xí kē xué 。"},
  { "w": "待", "p": "等待", "s": "我在等待你的回复。", "wp": "dài", "pp": "děng dài", "sp": "wǒ zài děng dài nǐ de huí fù 。"},
  { "w": "造", "p": "制造", "s": "这辆汽车是中国的工厂制造的。", "wp": "zào", "pp": "zhì zào", "sp": "zhè liàng qì chē shì zhōng guó de gōng chǎng zhì zào de 。"},
  { "w": "视", "p": "视力", "s": "我的视力很好。", "wp": "shì", "pp": "shì lì", "sp": "wǒ de shì lì hěn hǎo 。"},
  { "w": "基", "p": "基础", "s": "基础知识很重要。", "wp": "jī", "pp": "jī chǔ", "sp": "jī chǔ zhī shí hěn zhòng yào 。"},
  { "w": "具", "p": "具体", "s": "你能说得具体一点吗？", "wp": "jù", "pp": "jù tǐ", "sp": "nǐ néng shuō dé jù tǐ yī diǎn ma ？"},
  { "w": "价", "p": "价格", "s": "这件衣服的价格很贵。", "wp": "jià", "pp": "jià gé", "sp": "zhè jiàn yī fú de jià gé hěn guì 。"},
  { "w": "反", "p": "反对", "s": "我反对你的意见。", "wp": "fǎn", "pp": "fǎn duì", "sp": "wǒ fǎn duì nǐ de yì jiàn 。"},
  { "w": "考", "p": "考试", "s": "我正在准备考试。", "wp": "kǎo", "pp": "kǎo shì", "sp": "wǒ zhèng zài zhǔn bèi kǎo shì 。"},
  { "w": "据", "p": "根据", "s": "根据天气预报，明天会下雨。", "wp": "jù", "pp": "gēn jù", "sp": "gēn jù tiān qì yù bào ， míng tiān huì xià yǔ 。"},
  { "w": "选", "p": "选择", "s": "我选择了这个苹果。", "wp": "xuǎn", "pp": "xuǎn zé", "sp": "wǒ xuǎn zé le zhè gè pín guǒ 。"},
]